services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    environment:
      - PORT=4000
    volumes:
      - ./app/calorieHistory.csv:/app/calorieHistory.csv     # persist CSV
      - ./app:/app:ro    